### ISSUE TITLE
Add git tag 1.0.0 for your project

### ISSUE THREAD

**Issue by LAV45** [foxypkg/foxy#1]
Add git tag 1.0.0 for your project.

**Comment by francoispluchino** [comment]
Foxy under development. I'm currently cutting the code cleanly, doing all the unit tests, and tomorrow I think I will can add a missing feature.

**Comment by schmunk42** [comment]
A 0.1.0 or 1.0.0-alpha1 would be fine.

**Comment by LAV45** [comment]
In the documentation it is proposed to install the version `1.0.0` but in fact it does not exist

**Comment by francoispluchino** [comment]
Add the `dev` flag in version: `1.0.0@dev` or add in your `composer.json`:

```json
{
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

These values are not the default values for Composer (`stable` by default). It is a choice by the Composer's team that I understand, but which I do not adhere to. The other dependency manager allow by default an installation of the libraries in development. And the process is much more fluid. Well, that's another story ...

I have not added the flag in the doc because it is only for a few days.

Is it really necessary to update the doc for a flag with `composer require foxy/foxy:"^1.0.0@dev"`?

**Comment by francoispluchino** [comment]
The Foxy's version [v1.0.0-beta1](https://github.com/foxypkg/foxy/releases/tag/v1.0.0-beta1) is released.
